spring.application.name=resume-parser
spring.main.web-application-type=servlet

# Groq API Config (Loaded from .env or System Environment)
groq.base.url=${GROQ_BASE_URL:https://api.groq.com/openai/v1/chat/completions}
groq.api.key=${GROQ_API_KEY:}

server.port=8081

# Security & Error Handling Settings
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never
logging.level.org.springframework.web=INFO
logging.level.com.resume_parser=DEBUG

# Multipart File Upload Settings
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB